#!/usr/bin/env node

if(require.main == module){
	var fs= require("fs"),
	  streamArray= require("stream-array"),
	  argv= require("yargs")
	    .default('keys', 'key,value')
	    .alias('keys', 'k')
	    .argv,
	  YamlWriter= require("./yaml-writer"),
	  keys= argv.keys.split(",")

	try{
		var file= fs.readFileSync("/dev/stdin", "utf8"),
		  json= JSON.parse(file)
		if(!(json instanceof Array))
			throw "Input not an array"
		console.log("KEY",keys)
		streamArray(json).pipe(new YamlWriter({keys:keys})).pipe(process.stdout)
	}catch(ex){
		console.error(ex, ex.stack)
		process.exit(1)
	}
}
