#!/usr/bin/env node

if(require.main == module){
	var byline= require("byline"),
	  RcReader= require("./rc-reader"),
	  RcReader2= require("./rc-reader-2"),
	  YamlWriter= require("./yaml-writer")

	var stdin= process.stdin,
	  stdout= process.stdout,
	  byliner= byline.createStream(null, {keepEmptyLines: true}),
	  rcReader= new RcReader(),
	  yamlWriter= new YamlWriter()
	stdin.pipe(byliner).pipe(rcReader).pipe(yamlWriter).pipe(stdout)
}
